### ISSUE TITLE
Insertion error: Object was not added to Weaviate

### ISSUE THREAD

**Issue by TheBritishSabrina** [semi-technologies/weaviate-python-client#110]
When inserting vectors to Weaviate instance, I got this error, which I couldn't find in the python client: `Object was not added to Weaviate`.

**Context** 
Testing Weaviate for large-scale vector search

**Action** 
Inserting 100k random 150-dimensional vectors to Weaviate instance that already contained 100k vectors

**Configuration** 
Weaviate instance on kubernetes cluster, with one Weaviate node and one contextionary node

**Version** 
Weaviate python client v3.2.5

Previous actions: I tried batching vectors, but ran into the error: `The 'objects' creation was cancelled because it took longer than the configured timeout of 20s. Try reducing the batch size (currently 1000) to a lower value. Aim to on average complete batch request within less than 10s`. I reduced the batch size to 500 and then 100, but kept having the same problem.

**Comment by bobvanluijt** [comment]
cc: @StefanBogdan

**Comment by StefanBogdan** [comment]
Hi @TheBritishSabrina , this error is thrown whenever a batch creation throws a `TimeoutError`. This is unlikely a python problem, it seems that weaviate is take some time creating all the objects from the batch. This could be because Weaviate does some tasks in background and cannot handle all the objects at the moment in the given time, another cause could be the Contextionary, more specific the resources allocated to it. Could you please share the Weaviate version that you use, along with the resources allocated (for Weaviate and Contextionary). 

Also checking the Weaviate logs can give us more context of the why it happens. Are there any unusual activity?

Side note: The `Batch` object take an [timeout_retires](https://weaviate-python-client.readthedocs.io/en/v3.2.5/weaviate.batch.html#weaviate.batch.Batch.configure) argument that might help you in this case.

**Comment by TheBritishSabrina** [comment]
Hi @StefanBogdan, we're using Weaviate v1.10.1 and we have a contextionary but are using our own vector embeddings. 

Resources are:
- Weaviate pod: 1Gb
- Contextionary pod: 5Gb

This problem hasn't happened in a while but started again yesterday, when we were trying to insert into multiple classes - so could be a memory issue?

The logs show a lot of restarts and `lsm_recover_from_active_wal` actions. What does this indicate?

**Comment by StefanBogdan** [comment]
Hi @TheBritishSabrina , this could indeed be a memory issue. Did the weaviate pod ever restarted? If yes, what was the exit code? Also do you monitor resources usage?

Since you have your own vectors, I do not see why you would need Contextionary. Is there a reason to use it?

**Comment by StefanBogdan** [comment]
I am closing this issue since it is not a python-client related.
