### ISSUE TITLE
Allow setting custom vector in single and batch create object

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate-python-client#47]
## Background

With the changes for `v1` we have introduced the module system in Weaviate, which also allows for setting the vectorizer on a per-class basis. For example, with the app-wide config `DEFAULT_VECTORIZER_MODULE=text2vec-contextionary` - which is currently present on all docker-compose files we publish - the vectorizer is always set to `text2vec-contextionary`. However it can be overwritten. 

It is also possible to explicitly set the vectorizer to `none`. In this case, Weaviate doesn't do any vectorization, but expects the user to provide the vectors. This is one way of using Weaviate with vectors coming from any ML model - without having to write a full module for it.

## Goals 

* [ ] **The user can specify a custom vector when creating a single or batch object.**
   *Note: Weaviate will only accept the vector if the `vectorizer` is set to `none`. However, the client does not need to validate this explicitly and can just pass through any errors coming from Weaviate*

## Nice to Have
* [ ] **Support typical python standards**
  I think there are a few constructs in some of the common libraries for vectors, such as `pytorch.Tensor` and an eqivalent in `numpy`. It would be cool if the client could support the most common out of the box

## Weaviate API

You can simply specify the vector at the root level, here's an example with curl

```
curl -s localhost:8080/v1/schema -H 'content-type: application/json' \
  -d '{"class": "TestClass", "vectorizer":"none", "properties":[{"name": "name", "dataType": ["string"]}]}' 

curl -s localhost:8080/v1/objects -H 'content-type: application/json' \
  -d '{"class": "TestClass", "vector": [0,1], "properties": {"name":"hello world"}}' 
```

If we then check the object with the `?include=vector` option, the custom vector is present:

![image](https://user-images.githubusercontent.com/8974479/106251985-fb024f80-6215-11eb-97a6-4fd574a9b83a.png)

**Comment by StefanBogdan** [comment]
This feature can be added to the python client in two different ways:
1. Due to the current design of the package and class relations, this feature can be added by creating a `Schema` instance inside the `DataObject` and `Batch` class. Then every time we want to add an object the method `Schema.get()` should be called and then check if the class `vectorizer` is `"none"`inside the schema. This method is very slow and requires a lot of calls of the `Schema.get()` which will reduce the performance.

2. The second method requires redesigning the `Schema` class in such a manner that it has a `Schema.schema` attribute that is updated ONLY when the schema is modified. Also the schema can be modified by the class `Property` that currently is not linked to `Schema` class at all. This means that `Property` class should be moved inside the `Schema` class (`Property` being an inner class). This will make the `Property` a part of the `Schema` as it is supposed to be, not am isolated class. NOTE: The current implementation of the `Schema` has an instance attribute of the `Property` class, for this solution this is going to be the only way to create a schema, i.e. only through `Schema.Property`(accessing class) or `Schema().property`(accessing already existing instance).

I prefer the second one since it will not require to call the `Schema.get()` method every time we add an object.  Of course this means that we introduce breaking changes to weaviate client and it is going to be published as version `2.1.0`(I also want to fix this [issue](https://github.com/semi-technologies/weaviate-python-client/issues/45) with the `2.1.0`). The first method is going to be just a patch, version `2.0.3`.

@etiennedi What do you think about this? Also, what do you think about this [issue](https://github.com/semi-technologies/weaviate-python-client/issues/45), does it make any sense?
