### ISSUE TITLE
Possible backward incompatibility

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate-python-client#49]
If I try to [import this dataset](https://github.com/semi-technologies/DEMO-NewsPublications) with python client `2.4.0` I get the following error: 

```
ValueError: Not valid 'uuid' or 'uuid' can not be extracted from value
```

However, if I downgrade to the client version specified in the `requirements.txt` (`2.0.2`), the import works fine.

I don't now if this is an issue with the client or with the repository. Thanks for investigationg.

**Comment by StefanBogdan** [comment]
The error is caused by the `Batcher.add_references` method. With weaviate v2.3.0 (I think) the `Batcher.add_references` arguments were permuted to match the same sequence as the `ReferenceBatchRequest.add`. The [DEMO-NewPapers](https://github.com/semi-technologies/DEMO-NewsPublications) used unnamed arguments for the `Batcher.add_references` and with the new argument sequence it failed. I fixed the Demo by making the method calls with named arguments.
