### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate-python-client#5]
All documentation should go [here](https://github.com/semi-technologies/semi-website/tree/develop/_guides) a `./weaviate-clients/python/current`.

cc: @laura-ham is responsible for docs.

**Comment by fefi42** [comment]
@bobvanluijt Not sure what this means since the link is broken. There is a merge request for a getting started guide feel free to change it. The autogenerated documentation can be found at: https://semi-technologies.github.io/weaviate-python-client/html/index.html
Although it still could be improved alot, feel free to create an issue for concrete steps.

**Comment by bobvanluijt** [comment]
Yeah, the location is outdated.

The important thing is that we want _all_ docs on the website, @laura-ham and I harvested this for our doc sprint and will take it with us.

but this is great, thanks mate 👍
